### ISSUE TITLE
pretrained model load error

### ISSUE THREAD

**Issue by Liujingxiu23** [zhangyongmao/VISinger2#10]
I downloaded the pretrained model and use egs/visinger2/config.json, but errors occur when load the model using the codel in util "model.load_state_dict(new_state_dict)".

RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
        size mismatch for dec.downs.0.bias: copying a param with shape torch.Size([34]) from checkpoint, the shape in current model is torch.Size([66]).
        size mismatch for dec.downs.0.weight_g: copying a param with shape torch.Size([34, 1, 1]) from checkpoint, the shape in current model is torch.Size([66, 1, 1]).
        size mismatch for dec.downs.0.weight_v: copying a param with shape torch.Size([34, 34, 4]) from checkpoint, the shape in current model is torch.Size([66, 66, 4]).

**Comment by zhangyongmao** [comment]
Sorry for this error, this is due to the different configuration in the config.json file, you can directly change the "n_harmonic" in config.json to 32 to solve this problem. I will modify this bug later.

**Comment by Liujingxiu23** [comment]
the model can not be load successfully when  n_harmonic to 32.
