### ISSUE TITLE
decoder condition和论文中不一致

### ISSUE THREAD

**Issue by iehppp2010** [zhangyongmao/VISinger2#16]
您好，非常感谢您开源的代码。
我发现代码中
https://github.com/zhangyongmao/VISinger2/blob/master/egs/visinger2/models.py#L976
这里的decoder_condition和论文中concat noise和harm的操作不一致
<img width="421" alt="image" src="https://github.com/zhangyongmao/VISinger2/assets/22955379/1ea987a9-6acc-4ee8-89e9-a80b7e2b2f4e">
是做过实验，这么做效果更好么？

**Comment by zhangyongmao** [comment]
> 您好，非常感谢您开源的代码。 我发现代码中 https://github.com/zhangyongmao/VISinger2/blob/master/egs/visinger2/models.py#L976 这里的decoder_condition和论文中concat noise和harm的操作不一致 <img alt="image" width="421" src="https://user-images.githubusercontent.com/22955379/246046069-1ea987a9-6acc-4ee8-89e9-a80b7e2b2f4e.png"> 是做过实验，这么做效果更好么？

是的。在最早提交的版本中使用了跟论文一样的concat操作，但是我在后续实验中发现只用单个的sin信号效果会更好一点，所以进行了替换。

**Comment by iehppp2010** [comment]
好的，谢谢解答
