### ISSUE TITLE
关于实验结果评估的问题

### ISSUE THREAD

**Issue by Weixy24** [zhangyongmao/VISinger2#29]
您好，感想您的代码，注意到您论文中在实验结果中有两个客观指标F0-RMSE和Dur-RMSE，请问这两个指标具体是怎么计算的呢？在您提供的代码中没有找到相应的评估代码，可以提供一下吗？非常感谢

**Comment by zhangyongmao** [comment]
您好！F0-RMSE计算流程是首先使用真实时长输入模型来合成音频，然后分别使用基频提取工具提取合成音频与真实音频的F0，最后计算二者的RMSE-均方根误差。Dur-RMSE的计算流程是将时长预测器的预测结果保存下来，计算预测时长与真实时长的RMSE。评估代码可以根据这个流程来实现。

**Comment by Weixy24** [comment]
感谢您的解答！我按照流程能够复现出Dur-RMSE的结果了，但是F0-RMSE似乎还有一点差异，是有一些细节需要注意吗？或者可以提供一下这方面的代码吗？

**Comment by zhangyongmao** [comment]
F0-RMSE需要注意将提取出的0不计入计算结果，基频为0一般对应静音或者轻音

**Comment by Weixy24** [comment]
谢谢解答！
