### ISSUE TITLE
关于gtdur的累计误差问题

### ISSUE THREAD

**Issue by innnky** [zhangyongmao/VISinger2#5]
https://github.com/zhangyongmao/VISinger2/blob/86c49ff670affa6e7d66c82a1686e9df97c881d5/egs/visinger2/dataset.py#L138

**Comment by innnky** [comment]
我注意到您的代码在对原始的秒级的gtdur转换成帧级别时，是直接对每一个音素计算出的时长帧数取整，但是这样每一个音素的取整误差就会累积，一句音频累计下来可能会有几十帧的误差，我看到您在后面的代码也考虑了这个问题，丢弃了累计误差超过40帧的数据，但其实或许换个方式转换gtdur，例如这样
acc_duration = np.ceil(np.cumsum(gtdurs) / (self.hps.data.hop_size / self.hps.data.sample_rate))
acc_duration = np.append(0, acc_duration)
gtdurs = np.diff(acc_duration)
这种先统计累计精确时间最后取整的方式可以避免累计误差，可以保证音频帧数误差最大为1

**Comment by zhangyongmao** [comment]
感谢您的批评指正，我会尝试修正
