### ISSUE TITLE
对dsp_wav做频谱loss有什么用？直接对final result做GAN、feature和L1 loss不就行了吗？

### ISSUE THREAD

**Issue by splinter21** [zhangyongmao/VISinger2#7]

**Comment by zhangyongmao** [comment]
对dsp wav算loss是为了约束dsp wav，也是为了让z中包含更多有关幅度谱的信息。如果不对dsp wav算loss的话预计dsp wav就不会有可懂度，但是dsp wav里的周期部分的sin信号应该也可以为final wav提供指导。
