### ISSUE TITLE
为什么论文里vocoder用了LSTM但是代码里注释掉了没用？

### ISSUE THREAD

**Issue by splinter21** [zhangyongmao/VISinger2#8]
![image](https://user-images.githubusercontent.com/26759495/214269210-2a406c79-bd87-4b7e-9919-2f599410c91e.png)
![image](https://user-images.githubusercontent.com/26759495/214269242-089f090b-6d46-42f9-94f7-9009ac9d306b.png)

**Comment by zhangyongmao** [comment]
因为LSTM在某些torch环境里训练时候容易报错，所以替换掉了
